// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfdlcextxcuuujuwqwug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mZGxjZXh0eGN1dXVqdXdxd3VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjQ2OTMsImV4cCI6MjA2NTQwMDY5M30.YIA--14T_GxtNamW5jy8VAJElwDaz2Z_clmLJTKA-ps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);